version: "3.9"

services:
  challenge:
    image: challenge
    restart: unless-stopped
    build: .
    volumes:
      - .:/home/node/app
      - /node/app/node_modules
    ports:
      - "3000:3000"
    
